name: Ruby
on:
  pull_request:
    paths:
      - .github/workflows/ruby.yml
      - '.mdlrc'
      - '**/*.rb'
      - Gemfile
      - Gemfile.lock
      - Rakefile
  push:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Standard
        run: bundle exec rake lint:ruby
